### ISSUE TITLE
throttle-set security

### ISSUE THREAD

**Issue by avalanche1** [zeroasterisk/Meteor-Throttle#13]
`throttle-set(key, expireInSec) --> Throttle.set()`
If user knows his associatied key, eg connectionId - he can set a new expiration - isnt it a vulnerability?

**Comment by zeroasterisk** [comment]
not really - `Throttle.set()` is only available on the server.
https://github.com/zeroasterisk/Meteor-Throttle/blob/master/throttle.js#L180

**Comment by zeroasterisk** [comment]
@avalanche1 want to review that PR #14 for me?
